trigger:
- master

strategy:
  matrix:
    Linux_Py36:
      imageName: 'ubuntu-16.04'
      python.version: '3.6'
    Windows_Py36:
      imageName: 'vs2017-win2016'
      python.version: '3.6'
    Mac_Py36:
      imageName: 'macOS-10.13'
      python.version: '3.6'
    Linux_Py37:
      imageName: 'ubuntu-16.04'
      python.version: '3.7'
    Windows_Py37:
      imageName: 'vs2017-win2016'
      python.version: '3.7'
    Mac_Py37:
      imageName: 'macOS-10.13'
      python.version: '3.7'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
    python -m pip install pandas
    pip list
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines pytest-cov
    python setup.py build
    python setup.py install
    pytest -sv --cov=./
  displayName: 'Test'

- script: |
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Upload coverage report'