trigger:
- master

strategy:
  matrix:
    Linux_Py36:
      imageName: 'ubuntu-16.04'
      python.version: '3.6'
    #Windows_Py36:
    #  imageName: 'vs2017-win2016'
    #  python.version: '3.6'
    #Mac_Py36:
    #  imageName: 'macOS-10.13'
    #  python.version: '3.6'
    #Linux_Py37:
    #  imageName: 'ubuntu-16.04'
    #  python.version: '3.7'
    #Windows_Py37:
    #  imageName: 'vs2017-win2016'
    #  python.version: '3.7'
    #Mac_Py37:
    #  imageName: 'macOS-10.13'
    #  python.version: '3.7'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
    pip list
  displayName: 'Install dependencies'

- script: |
    python -m pip install pytest pytest-azurepipelines pytest-cov pandas
    python setup.py build
    python setup.py install
  displayName: 'Install Test dependencies'

- script: |
    pytest -sv
  displayName: 'Test'
  condition: ne('Job Linux_Py36', variables['Agent.JobName'])

- script: |
    pytest tests/ --cov=ndsplines -–cov-report xml:cov.xml
    bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN) -f./cov.xml
  displayName: 'Test With Coverage'
  condition: eq('Job Linux_Py36', variables['Agent.JobName'])